### PR TITLE
Newer Terraforms need booleans to be defined as strings.

### PR DESCRIPTION
**Pull request by juliandunn**
Otherwise you get:

```
An error has occurred while serializing the variables for uploading:
invalid type bool
```

### CODE REVIEW

**Comment by mengesb** [comment]
When did this come of? I'm still using the boolean in current plans with v0.7.11 now without error

**Comment by juliandunn** [comment]
I'm on 0.7.11 as well. I had to make this change otherwise I got the aforementioned error.

**Comment by mengesb** [comment]
My terraform is running as-is and kitchen tests your last PR successfully without stringifying the booleans.

**Comment by mengesb** [comment]
```
Finished in 1.16 seconds (files took 1.58 seconds to load)
34 examples, 0 failures
```

Looking into the booleans...
```hcl
$ grep -A5 -B5 ' true' variables.tf                                                                                                                    [ruby-2.0.0p648]
  default          = "false"
}
variable "chef_log" {
  #type             = "boolean"
  description      = "Log chef provisioner to file"
  default          = true
}
variable "chef_org" {
  type             = "map"
  description      = "Chef organization settings"
  default          = {
--
--
  }
}
variable "instance_public" {
  #type             = "boolean"
  description      = "Associate a public IP to the instance"
  default          = true
}
variable "instance_tag_desc" {
  type             = "string"
  description      = "EC2 instance description tag"
  default          = "Created using Terraform (tf_chef_server)"
--
--
}
variable "instance_volume" {
  type             = "map"
  description      = "EC2 instance root volume settings"
  default          = {
    delete         = true
    size           = 20
    type           = "gp2"
  }
}
```

**Comment by juliandunn** [comment]
Ok. I'm not sure why it won't work for me. But anyway, Terraform recommends that people don't use bare booleans, and instead use strings, so it could be a good thing to fix: https://github.com/hashicorp/terraform/pull/9751

**Comment by mengesb** [comment]
One method you can use to override the variables would be in terraform.tfvars:
```hcl
instance_volume = {
  delete = "true"
  size = "20"
  type = "gp2"
}
instance_public = "true"
chef_log = "true"
```

**Comment by mengesb** [comment]
OK i can see the point. I had filed hashicorp/terraform#6447 and do recall that referenced PR. Didn't recall that the effect was to stringify the booleans yet

**Comment by mengesb** [comment]
As you can also see in the code; i was preparing for the later update (`type = "boolean"`)

**Comment by juliandunn** [comment]
yeah. I'm using the `terraform.tfvars` override and using stringified booleans in there, which might explain the issue -- perhaps Terraform got confused at the two styles.

**Pull request merged**
